Controller/AdminServicios.php, Controller/ListServicioAT.php, Lib/Export/PDFserviciosExport.php, Model/ServicioAT.php, Table/serviciosat.xml, XMLView/ConfigServicios.xml, XMLView/EditServicioAT.xml
A number of improvements and restructuring have been completed in the configuration system.
- The tables with auxiliary data for the configuration of the services are grouped together in a single configuration option in the administration menu.
- Added different configuration options, which allow to indicate which options should be included in the printing of the service report.
- Added the possibility of indicating a fixed text to be printed in the footer of the service report.
- Added the possibility of reporting up to four machines in the service part.
=> Set of improvements

Extension/Controller/Randomizer.php, Init.php, Lib/Random/Servicios.php
Refactorize code for new Randomizer system.
=> Add Randomizer system

Init.php, Lib/Export/PDFserviciosExport.php
método update() para generar el rol y permisos para este plugin
- También añadimos todos los uses que necesita.
=> - Añadimos al init.php el método createRoleForPlugin(), llamado desde el

Lib/Export/PDFserviciosExport.php
[Tarea #1957](https://facturascripts.com/roadmap/EditTask?code=1957)
=> Tarea #1957 - En el pdf mostrar el código en vez del id del servicio.

Lib/ServiceToInvoice.php
[Tarea #1958](https://facturascripts.com/roadmap/EditTask?code=1958)
=> Tarea #1958 - Al crear el documento del servicio enlazar con el mismo proyecto, si tiene.

Lib/Tickets/Service.php
[Tarea #2995](https://facturascripts.com/roadmap/EditTask?code=2995)
=> Tarea #2995 - Corregido pie del ticket del servicio

.gitignore, Controller/ListServicioAT.php, Data/Lang/ES/servicioat_tipos.csv, Model/ServicioAT.php, Model/TipoAT.php, Table/serviciosat.xml, Table/serviciosat_tipos.xml, XMLView/EditServicioAT.xml, XMLView/EditTipoAT.xml, XMLView/ListServicioAT.xml, XMLView/ListTipoAT.xml
[Tarea #3502](https://facturascripts.com/roadmap/3502)
=> Tarea #3502 - Corregidos los tipos de los servicios

Lib/Export/PDFserviciosExport.php, XMLView/ConfigServicios.xml
[Tarea #2485](https://facturascripts.com/roadmap/2485)
[Tarea #2486](https://facturascripts.com/roadmap/2486)
=> Tarea #2485 y #2486 - Permite imprimir el agente y usuario asignado y detalles del trabajo

Controller/NewServicioAT.php, View/NewServicioAT.html.twig
[Tarea #2780](https://facturascripts.com/roadmap/2780)
=> Permite crear servicios sin máquinas

Controller/NewServicioAT.php, Model/ServicioAT.php, View/NewServicioAT.html.twig
[Tarea #3521](https://facturascripts.com/roadmap/3521)
=> Tarea #3521 - Nuevo diseño para nuevos servicios

Controller/EditServicioAT.php, Extension/Controller/CopyModel.php, Init.php, View/CopyServicioAT.html.twig
[Tarea #3526](https://facturascripts.com/roadmap/3526)
=> Tarea #3526 - Permite copiar servicios

Init.php, Lib/Export/PlantillasPDFserviciosExport.php
[Tarea #3390](https://facturascripts.com/roadmap/3390)
=> Tarea #3390 - Plantilla pdf compatible con plantillasPDF

View/NewServicioAT.html.twig, XMLView/ConfigServicios.xml
[Tarea #2780](https://facturascripts.com/roadmap/2780)
=> Tarea #2780 - Configurar nuevo servicio sin máquina

Controller/ListServicioAT.php, Model/Join/TrabajoAT.php, Model/Join/TrabajoServicio.php, XMLView/ListTrabajoAT.xml
[Tarea #2152](https://facturascripts.com/roadmap/2152)
=> Tarea #2152 - Añadido JoinModel para los trabajos

Controller/EditServicioAT.php, Controller/ListServicioAT.php, Model/TrabajoAT.php, XMLView/EditTrabajoAT.xml
[Tarea #3600](https://facturascripts.com/roadmap/3600)
=> Tarea #3600 - Añadidos filtros al listado de trabajos

Controller/NewServicioAT.php, View/NewServicioAT.html.twig
[Tarea #3777](https://facturascripts.com/roadmap/3777)
=> Tarea #3777 - Añadir fabricante al crear máquina desde el modal

Controller/NewServicioAT.php, View/NewServicioAT.html.twig, XMLView/ListMaquinaAT.xml
[Tarea #3795](https://facturascripts.com/roadmap/3795)
=> Tarea #3795 - Mostrar máquinas sin cliente al crear un servicio

Extension/Controller/EditProducto.php, Init.php
[Tarea #3637](https://facturascripts.com/roadmap/3637)
=> Tarea #3637 - Mostrar los trabajos en la ficha del producto

Init.php, Lib/Export/PDFserviciosExport.php, Lib/Export/PlantillasPDFserviciosExport.php, Lib/Tickets/Service.php, XMLView/ConfigServicios.xml
[Tarea #3803](https://facturascripts.com/roadmap/3803)
**NECESITA EL PR** https://github.com/FacturaScripts/tickets/pull/30
=> Tarea #3803 - Mejorada la impresión de tickets

.gitignore, Controller/AdminServicios.php, Controller/EditCategoriaAT.php, Controller/EditServicioAT.php, Data/Lang/ES/serviciosat_categorias.csv, Init.php, Model/CategoriaAT.php, Model/CheckAT.php, Model/ServicioCategoriaAT.php, Model/ServicioCheckAT.php, Table/serviciosat_categorias.xml, Table/serviciosat_checks.xml, Table/serviciosat_serviciocategorias.xml, Table/serviciosat_serviciochecks.xml, XMLView/EditCategoriaAT.xml, XMLView/EditCheckAT.xml, XMLView/EditServicioCategoriaAT.xml, XMLView/EditServicioCheckAT.xml, XMLView/ListCategoriaAT.xml
**Añadidas categorías**
- Se añade dentro del panel de configuración del plugin la pestaña de categorías.
- Cada categoría puede tener distintos checks o tareas a verificar al realizar los servicios.
- Para añadir o modificar los checks o verificaciones se tiene que editar una categoría.
**Añadir categorias a los servicios**
- Se añaden nuevas pestañas a la edición del servicio para la asignación de categorías al servicio y sus verificaciones.
- Si la categoría tiene verificaciones, se añaden al servicio.
- Si el servicio no tiene categorías o las categorías añadidas no tienen verificaciones no se muestra las verificaciones.
**Nota:**
_Se han añadido las siguientes etiquetas que necesitan traducción:_
* "checks": "Comprobaciones",
* "verification": "Verificación",
* "verifications": …
=> Añadir Categorías y Verificaciones
